# Generated by Django 4.2.7 on 2025-11-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('women_support', 'Women Support'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='charity_logos/')),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='charity_api_name_93d72f_idx'), models.Index(fields=['category'], name='charity_api_categor_00d005_idx'), models.Index(fields=['location'], name='charity_api_locatio_da5c2d_idx')],
            },
        ),
    ]
